title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
onion:
  date_format: "%Y-%m-%d"

# generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    devto: jekyll
    dribbble: jekyll
    facebook: jekyll
    flickr:   jekyll
    instagram: jekyll
    linkedin: jekyll
    pinterest: jekyll
    youtube: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    youtube_channel_name: CloudCannon
    telegram: jekyll
    googleplus: +jekyll
    microdotblog: jekyll
    keybase: jekyll

# generate crypto wallets in footer
  crypto_wallets:
    bitcoin:
    etherium:

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md

# Build settings
theme: jekyll-theme-onion

plugins:
 - jekyll-feed
 - jekyll-seo-tag


kramdown:
  input: Kramdown
  syntax_highlighter: rouge

show_excerpts: true

sass:
  sass_dir:           _sass
  style:              compressed

permalink: pretty
